### ISSUE TITLE
RFE: provide a centos7 based version ? C8 Stream version?

### ISSUE THREAD

**Issue by truatpasteurdotfr** [intel/oneapi-containers#12]
CentOS-8 is going EOL at the end of 2021, would you consider also pushing for a legacy CentOS-7 version and CentOS-8 stream one, as both will only EOL in 2024.

**Comment by gorozco1** [comment]
Hello @truatpasteurdotfr , we are not going to build CentOS-8 containers for 2022.1 release, we plan to build and release containers based on Rocky Linux around march 2022

**Comment by truatpasteurdotfr** [comment]
Thank for the update on the RHEL8 clone chosen.  Will you also produce a CentOS-7 based version?

**Comment by unrahul** [comment]
Hi @truatpasteurdotfr the older containers are available on our repo for centos, for future versions, we are evaluating oses that have parity with Centos like Rocky and you can expect a binary compatible OS in regards to CentOS by the march of next year. We will not be releasing new solutions on CentOS 7 or 8.
