### ISSUE TITLE
dpcpp not found

### ISSUE THREAD

**Issue by tr3ysmith** [intel/oneapi-containers#14]
Pulled down the docker image of oneapi base today, and running dpcpp command says "not found".
intel/oneapi-basekit:latest

**Comment by luisfponce** [comment]
Hello @tr3ysmith,

Please find the latest  intel/oneapi-basekit

`docker pull intel/oneapi-basekit:2022.1.1-devel-ubuntu18.04`
or
`docker pull intel/oneapi-basekit:latest`

In this version you should see it available as:

```
root@0f93a4eaa9fc:/# dpcpp --version
Intel(R) oneAPI DPC++/C++ Compiler 2022.0.0 (2022.0.0.20211123)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/2022.0.1/linux/bin-llvm
```

**Comment by garymm** [comment]
Close this?

**Comment by tingleby** [comment]
Closing issue, please reopen if you are still having issues.
