### ISSUE TITLE
entrypoint fails with non-root user

### ISSUE THREAD

**Issue by adegomme** [intel/oneapi-containers#16]
Launching the last version of the containers is failing if another user than root is used.
The entrypoint specified is in /root/ and unreachable for normal users, and the command fails.
Using --entrypoint '' is a workaround, but then the environment is not setup correctly (maybe the issue of #14 ?).

The script to source should be placed somewhere reachable for all users (/tmp or with the other intel stuff in /opt, with correct permissions).

I personally preferred the previous version with ENV commands in the dockerfile, even if verbose, as they left the entrypoint free for other usages in containers using these as base.

**Comment by adegomme** [comment]
It's actually even worse, as the script is executed only when the container is launched, the environment variables are not available during the build steps : a container using FROM oneapi-hpckit:devel** is not able anymore to use the intel compilers to build anything during the build step, as they are not setup properly (and as it works properly when launching bash and doing the steps manually, it can be annoying to debug).

**Comment by luisfponce** [comment]
Hello @adegomme ,

Please find the latest [OneAPI images](https://hub.docker.com/r/intel/oneapi)  _(no entrypoint used in any oneapi container image, switch to `ENV` to avoid the scenario you planted)_

Kind regards

**Comment by tingleby** [comment]
As @luisfponce wrote, newer images do not have entrypoints set and went back to `ENV` style setup. 

Closing this issue.
