### ISSUE TITLE
Cannot build Dockerfile.ubuntu-18.04

### ISSUE THREAD

**Issue by ionutboscuintel** [intel/oneapi-containers#17]
The following packages have unmet dependencies:
 intel-level-zero-gpu : Depends: intel-igc-opencl (= 1.0.8517) but 1.0.1629709536 is to be installed
 intel-opencl : Depends: intel-igc-opencl (= 1.0.8517) but 1.0.1629709536 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by obedmr** [comment]
Hi @ionutboscuintel, thanks for reporting this issue, we're working with the release team in order to fix it.

In the meantime, you can install the following 2 dependencies before in order to meet that fixed dependency requirement
```
 apt install -y intel-igc-core=1.0.8517 intel-igc-opencl=1.0.8517
```

**Comment by obedmr** [comment]
Hi @ionutboscuintel,
The issue has been fixed by the release team, I've tested it in my own and it works. 
Would you mind taking a look in your side?
Thanks for your patience.

**Comment by ionutboscuintel** [comment]
Yes, this is fixed now. The issues can be closed. Thank you!
