### ISSUE TITLE
Are there any containers that support fpga?

### ISSUE THREAD

**Issue by cdyangzhenyu** [intel/oneapi-containers#18]
Are there any containers that support fpga? why not?

**Comment by luisfponce** [comment]
Hello @cdyangzhenyu,

Please feel free to take a look at [Intel Developer Zone -  FPGA](https://www.intel.com/content/www/us/en/developer/tools/oneapi/fpga.html).
I think you can use the benefits of Accelerate Your Data-Centric Workloads with FPGAs by using [OneAPI Basekit](https://hub.docker.com/r/intel/oneapi-basekit)

If you still having doubts please elaborate  a single question.

Kind regards.

**Comment by tingleby** [comment]
The FPGA stack for oneAPI is typically very large, 10s of GB which can be difficult to distribute/use in containers. We do not have any active plans to support FPGAs beyond cpu emulation in the oneAPI Images.

Closing this issue.
