### ISSUE TITLE
Add support for Ubuntu 20.04

### ISSUE THREAD

**Issue by skiselev** [intel/oneapi-containers#25]
Please add Docker file for building Ubuntu 20.04 docker images.
Note that Intel GPUs are not well supported under Ubuntu 18.04, so it is rather useless for anyone trying to use GPU in Ubuntu 18.04 Docker image

**Comment by gorozco1** [comment]
hi @skiselev  docker images and docker files with ubuntu 20.04 has been added in the last release.

**Comment by gorozco1** [comment]
ubuntu 20.04 containers released in 2022.2 release
