### ISSUE TITLE
aocl install failed within container

### ISSUE THREAD

**Issue by sungin-h** [intel/oneapi-containers#26]
aocl install intel_s10sx_pac
failed due to invalid install script for using within container.

docker image : intel/oneapi-basekit (Ubuntu 18.04)
host environment:
   OS : Ubuntu 18.04.06 LTS (kernel : 5.4.0-99-generic)
   FPGA : Intel FPGA PAC D5005 (intel_s10sx_pac)
   docker version :  20.10.7
   GPU : NVIDIA A100 (driver ver. 495.29.05, CUDA v11.5) // for just in case
   nvidia-docker : ver. 20.10.7 // for just in case
   **I setup host to use OpenCL and DPCPP for intel FPGA PAC D5005.**
docker command 
  $ sudo docker run -it --gpus all --device=/dev/dri --privileged intel/oneapi-basekit bash

First, I met the below errors:
   lspci : command not found
   Error: unsupported OS: Ubuntu 18.04 kernel 5.4.0-99-generic

To fix them,
   installed pciutils using $apt install pciutils;
   deleted kernel version checking in "install" script under .../oclfpga/board/intel_s10sx_pac/linux/libexec/
      and "sudo" keywords
   // I might install fpga addon via apt but not 100% sure.

Still, I met an error on setup_permissions.sh script failed. It leads to removing FCD and board packages. (I'm not sure but some of opae packages seem to be installed)
I copied FCD from the host and modified the path of .so files.

Now, I can use the FPGA PAC with a simple vector add a pre-compiled program within basekit container.

Can you provide a valid aocl script for containers?
Thank you.

**Comment by tingleby** [comment]
Hi @sungin-h we typically don't support the FPGA addons with the containers. I am going to close this ticket but if you'd like to re-open it, please leave a comment.
