### ISSUE TITLE
intercept-build missing from basekit container

### ISSUE THREAD

**Issue by ngaloppo** [intel/oneapi-containers#3]
The  `intercept-build` script is missing from the basekit container. 

https://software.intel.com/content/www/us/en/develop/documentation/get-started-with-intel-dpcpp-compatibility-tool/top.html#top_MIGRATION_MAKE_CMAKE

**Comment by deangithub** [comment]
For the Intel® DPC++ Compatibility Tool, please use the Intel® oneAPI Base Toolkit installer found at https://software.intel.com/oneapi.
