### ISSUE TITLE
Build docker hpckit container on M1 Mac.

### ISSUE THREAD

**Issue by whornsby82** [intel/oneapi-containers#32]
Hello all,

I'm having some issues running MPI jobs within the docker container on an M1 Mac.  Ive tried building an image to see if this rectifies this, but I can't get the Ubuntu containers to build, they generally fail with:
#13 5.127 Get:22 http://ports.ubuntu.com/ubuntu-ports focal-security/multiverse arm64 Packages [3253 B]
#13 5.170 Fetched 18.8 MB in 5s (3827 kB/s)
#13 5.170 Reading package lists...
#13 5.623 Reading package lists...
#13 6.045 Building dependency tree...
#13 6.140 Reading state information...
#13 6.153 E: Unable to locate package intel-oneapi-advisor
#13 6.153 E: Unable to locate package intel-oneapi-ccl-devel
#13 6.153 E: Unable to locate package intel-oneapi-compiler-dpcpp-cpp

Is arm64 supported? Or is there some tricks/tips?

Many thanks

William

**Comment by tingleby** [comment]
I'm afraid, arm64 is not support in the Intel oneAPI releases.
