### ISSUE TITLE
README.md contains links that are broken

### ISSUE THREAD

**Issue by mattcurf** [intel/oneapi-containers#4]
In the README.md it says

"Base Kit Dockerfile" (which is a link to https://github.com/intel/oneapi-containers/blob/master/images/basekit-devel-ubuntu18.04/Dockerfile), but that file does not exist in the repository

HPC Kit Dockerfile, IoT Kit Dockerfile, and AI Kit Dockerfile are also broken links

**Comment by deangithub** [comment]
Thank you. The links have been updated.
