### ISSUE TITLE
oneAPI Base Toolkit image no longer has cmake installed

### ISSUE THREAD

**Issue by lucasalavapena** [intel/oneapi-containers#51]
Firstly, thanks for providing the images, they have been useful :)

I am not sure if this was done intentionally or not, if it was done intentionally feel free to close the issue, it is just that most oneMKL examples are built with cmake. However, the base toolkit image no longer has cmake installed, it was removed in the [last commit](https://github.com/intel/oneapi-containers/commit/b005b11a762b96467e4efd569d7c8715cdcc30e2)

**Comment by tingleby** [comment]
Latest images include `cmake`
