### ISSUE TITLE
Dockerfile is not updated

### ISSUE THREAD

**Issue by den6** [intel/oneapi-containers#52]
Thanks for the great work with these containers.

Now, the version of oneAPI has been updated to 2023.2.1 two weeks ago, but the Dockerfile update is seems to be late.
I remember that the Dockerfile was updated late for a while, in 2023.2.0,
When do you plan to release a Dockerfile for 2023.2.1 ?

**Comment by gorozco1** [comment]
@den6 we just release 2024.0 containers

**Comment by den6** [comment]
Thank you kindly for letting me know that it has been updated !
I immediately built it and confirmed it works.
