### ISSUE TITLE
failed to build docker image with hpckit (Dockerfile.ubuntu-22.04)

### ISSUE THREAD

**Issue by weiyu11** [intel/oneapi-containers#54]
I got the error message as following:

 => [internal] load build definition from Dockerfile                                                    0.0s
 => => transferring dockerfile: 9.26kB                                                                  0.0s
 => [internal] load .dockerignore                                                                       0.0s
 => => transferring context: 2B                                                                         0.0s
 => [internal] load metadata for docker.io/library/ubuntu:22.04                                         0.8s
 => [internal] load build context                                                                       0.0s
 => => transferring context: 74.36kB                                                                    0.0s
 => CACHED [1/9] FROM docker.io/library/ubuntu:22.04@sha256:2b7412e6465c3c7fc5bb21d3e6f1917c167358449f  0.0s
 => [2/9] COPY third-party-programs.txt /                                                               0.0s
 => [3/9] RUN apt-get update && apt-get upgrade -y &&   DEBIAN_FRONTEND=noninteractive apt-get instal  35.6s
 => [4/9] RUN curl -fsSL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023  0.4s
 => [5/9] RUN echo "deb [signed-by=/usr/share/keyrings/intel-oneapi-archive-keyring.gpg] https://apt.r  0.2s 
 => [6/9] RUN apt-get update && apt-get upgrade -y &&   DEBIAN_FRONTEND=noninteractive apt-get install  9.5s 
 => [7/9] RUN curl -fsSL https://repositories.intel.com/graphics/intel-graphics.key | gpg --dearmor |   0.6s 
 => [8/9] RUN echo "deb [signed-by=/usr/share/keyrings/intel-graphics-archive-keyring.gpg arch=amd64]   0.3s 
 => ERROR [9/9] RUN apt-get update && apt-get upgrade -y &&   DEBIAN_FRONTEND=noninteractive apt-get i  8.9s 
------                                                                                                       
 > [9/9] RUN apt-get update && apt-get upgrade -y &&   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends     ca-certificates build-essential pkg-config gnupg libarchive13 openssh-server openssh-client wget net-tools git intel-basekit-getting-started intel-oneapi-advisor intel-oneapi-ccl-devel intel-oneapi-common-licensing intel-oneapi-common-vars intel-oneapi-compiler-dpcpp-cpp intel-oneapi-dal-devel intel-oneapi-dev-utilities intel-oneapi-dnnl-devel intel-oneapi-dpcpp-debugger intel-oneapi-ipp-devel intel-oneapi-ippcp-devel intel-oneapi-libdpstd-devel intel-oneapi-mkl-devel intel-oneapi-tbb-devel intel-oneapi-vtune intel-level-zero-gpu level-zero intel-hpckit-getting-started intel-oneapi-clck intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic intel-oneapi-compiler-fortran intel-oneapi-inspector intel-oneapi-itac intel-oneapi-mpi-devel  &&   rm -rf /var/lib/apt/lists/*:
#13 0.420 Get:1 https://apt.repos.intel.com/oneapi all InRelease [4451 B]
#13 0.491 Get:2 https://repositories.intel.com/graphics/ubuntu jammy InRelease [22.4 kB]
#13 0.511 Get:3 https://apt.repos.intel.com/oneapi all/main all Packages [103 kB]
#13 0.545 Get:4 http://ports.ubuntu.com/ubuntu-ports jammy InRelease [270 kB]
#13 0.680 Get:5 https://repositories.intel.com/graphics/ubuntu jammy/flex amd64 Packages [98.1 kB]
#13 1.286 Get:6 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease [119 kB]
#13 1.462 Get:7 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease [109 kB]
#13 1.626 Get:8 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease [110 kB]
#13 1.790 Get:9 http://ports.ubuntu.com/ubuntu-ports jammy/universe arm64 Packages [17.2 MB]
#13 4.835 Get:10 http://ports.ubuntu.com/ubuntu-ports jammy/restricted arm64 Packages [24.2 kB]
#13 4.838 Get:11 http://ports.ubuntu.com/ubuntu-ports jammy/multiverse arm64 Packages [224 kB]
#13 4.860 Get:12 http://ports.ubuntu.com/ubuntu-ports jammy/main arm64 Packages [1758 kB]
#13 5.090 Get:13 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 Packages [1276 kB]
#13 5.580 Get:14 http://ports.ubuntu.com/ubuntu-ports jammy-updates/multiverse arm64 Packages [27.9 kB]
#13 5.583 Get:15 http://ports.ubuntu.com/ubuntu-ports jammy-updates/universe arm64 Packages [1166 kB]
#13 5.855 Get:16 http://ports.ubuntu.com/ubuntu-ports jammy-updates/restricted arm64 Packages [914 kB]
#13 6.744 Get:17 http://ports.ubuntu.com/ubuntu-ports jammy-backports/universe arm64 Packages [30.7 kB]
#13 6.747 Get:18 http://ports.ubuntu.com/ubuntu-ports jammy-backports/main arm64 Packages [77.8 kB]
#13 6.767 Get:19 http://ports.ubuntu.com/ubuntu-ports jammy-security/main arm64 Packages [1012 kB]
#13 6.898 Get:20 http://ports.ubuntu.com/ubuntu-ports jammy-security/restricted arm64 Packages [906 kB]
#13 7.025 Get:21 http://ports.ubuntu.com/ubuntu-ports jammy-security/multiverse arm64 Packages [23.4 kB]
#13 7.026 Get:22 http://ports.ubuntu.com/ubuntu-ports jammy-security/universe arm64 Packages [904 kB]
#13 7.461 Fetched 26.4 MB in 7s (3639 kB/s)
#13 7.461 Reading package lists...
#13 7.837 Reading package lists...
#13 8.183 Building dependency tree...
#13 8.263 Reading state information...
#13 8.275 Calculating upgrade...
#13 8.359 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
#13 8.382 Reading package lists...
#13 8.730 Building dependency tree...
#13 8.810 Reading state information...
#13 8.816 E: Unable to locate package intel-oneapi-advisor
#13 8.816 E: Unable to locate package intel-oneapi-ccl-devel
#13 8.816 E: Unable to locate package intel-oneapi-compiler-dpcpp-cpp
#13 8.816 E: Unable to locate package intel-oneapi-dal-devel
#13 8.816 E: Unable to locate package intel-oneapi-dev-utilities
#13 8.816 E: Unable to locate package intel-oneapi-dnnl-devel
#13 8.816 E: Unable to locate package intel-oneapi-dpcpp-debugger
#13 8.816 E: Unable to locate package intel-oneapi-ipp-devel
#13 8.816 E: Unable to locate package intel-oneapi-ippcp-devel
#13 8.816 E: Unable to locate package intel-oneapi-libdpstd-devel
#13 8.816 E: Unable to locate package intel-oneapi-mkl-devel
#13 8.816 E: Unable to locate package intel-oneapi-tbb-devel
#13 8.816 E: Unable to locate package intel-oneapi-vtune
#13 8.816 E: Unable to locate package intel-level-zero-gpu
#13 8.816 E: Unable to locate package level-zero
#13 8.816 E: Unable to locate package intel-oneapi-clck
#13 8.816 E: Unable to locate package intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic
#13 8.816 E: Unable to locate package intel-oneapi-compiler-fortran
#13 8.816 E: Unable to locate package intel-oneapi-inspector
#13 8.816 E: Unable to locate package intel-oneapi-itac
#13 8.816 E: Unable to locate package intel-oneapi-mpi-devel
------
executor failed running [/bin/sh -c apt-get update && apt-get upgrade -y &&   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends     ca-certificates build-essential pkg-config gnupg libarchive13 openssh-server openssh-client wget net-tools git intel-basekit-getting-started intel-oneapi-advisor intel-oneapi-ccl-devel intel-oneapi-common-licensing intel-oneapi-common-vars intel-oneapi-compiler-dpcpp-cpp intel-oneapi-dal-devel intel-oneapi-dev-utilities intel-oneapi-dnnl-devel intel-oneapi-dpcpp-debugger intel-oneapi-ipp-devel intel-oneapi-ippcp-devel intel-oneapi-libdpstd-devel intel-oneapi-mkl-devel intel-oneapi-tbb-devel intel-oneapi-vtune intel-level-zero-gpu level-zero intel-hpckit-getting-started intel-oneapi-clck intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic intel-oneapi-compiler-fortran intel-oneapi-inspector intel-oneapi-itac intel-oneapi-mpi-devel  &&   rm -rf /var/lib/apt/lists/*]: exit code: 100

**Comment by gorozco1** [comment]
@weiyu11 this was probably a hiccup in repos.intel.com, can you retry again?

**Comment by tingleby** [comment]
@weiyu11  Please try again

**Comment by weiyu11** [comment]
Still has the following error:
....................
#13 9.588 E: Unable to locate package intel-basekit
#13 9.588 E: Unable to locate package intel-level-zero-gpu
#13 9.588 E: Unable to locate package level-zero
#13 9.588 E: Unable to locate package intel-hpckit
------
executor failed running [/bin/sh -c apt-get update && apt-get upgrade -y &&   DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends     ca-certificates build-essential pkg-config gnupg libarchive13 openssh-server openssh-client wget net-tools git   intel-basekit intel-level-zero-gpu level-zero intel-hpckit  &&   rm -rf /var/lib/apt/lists/*]: exit code: 100

**Comment by tingleby** [comment]
Apologies, looking closely at your ticket, it looks like you are on a `arm64` machine. Intel oneAPI does not support those platforms.
Closing issue.
