### ISSUE TITLE
Missing level-zero-dev in basekit/Dockerfile.ubuntu-22.04

### ISSUE THREAD

**Issue by wozna** [intel/oneapi-containers#65]
I used image basekit/Dockerfile.ubuntu-22.04, but during building my application `-lze_loader` was not found, because there was no level-zero-dev package. 
After installing it, everything works correctly. I can see that image basekit/Dockerfile.ubuntu-20.04 installs it. Is it a mistake or you removed it on purpose, for saving memory or different reason?

**Comment by tingleby** [comment]
In the latest images, the level zero dev package should be installed by default.
