### ISSUE TITLE
intel/oneapi-basekit APT Repository not working 

### ISSUE THREAD

**Issue by mofosyne** [intel/oneapi-containers#70]
It appears there is a workaround for this as shown in this commit below, however you may want to consider regenerating your docker image with corrections to your latest APT Repository

https://github.com/intel-analytics/ipex-llm/commit/e0f401d97d14734de22467a24d5a6fd38f622eec (Credit to [simonlui](https://github.com/simonlui) for the heads up)

It appears that you switched to https://repositories.intel.com/graphics/ubuntu over https://repositories.intel.com/gpu/ubuntu

This issue is currently affecting a few repository so far:

* https://github.com/ggerganov/llama.cpp/issues/7507
* https://github.com/NCAR/micm/pull/527

The line you may need to change is located in https://github.com/intel/oneapi-containers/blob/master/images/docker/basekit/Dockerfile.ubuntu-22.04#L20 which looks like:

```dockerfile
RUN curl -fsSL https://repositories.intel.com/gpu/intel-graphics.key | gpg --dearmor | tee /usr/share/keyrings/intel-graphics-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/intel-graphics-archive-keyring.gpg arch=amd64] https://repositories.intel.com/gpu/ubuntu jammy/lts/2350 unified" > /etc/apt/sources.list.d/intel-graphics.list
```

It's clear that we will need to update the url and the gpg key for the above

----

Context: 
* https://hub.docker.com/r/intel/oneapi-basekit
* https://github.com/intel/oneapi-containers/tree/master/images/docker/basekit

**Comment by mofosyne** [comment]
FYI we are likely going to work around this via @airMeng PR https://github.com/ggerganov/llama.cpp/pull/7630
Which you may want to use as reference to update the main dockerfile

**Comment by mdreyesm** [comment]
the new images with the refreshed apt key are now available on dockerhub
