### ISSUE TITLE
hpckit 2024.1.0 Ubuntu 22.04 GPG error

### ISSUE THREAD

**Issue by jasonleekungfu** [intel/oneapi-containers#71]
Hi! I am using `intel/hpckit:2024.1.0-devel-ubuntu22.04` container as my base build. It was working just fine yesterday. But I got this error today:

`GPG error: https://repositories.intel.com/gpu/ubuntu jammy/lts/2350 InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 28DA432DAAC8BAEA`

The latest `intel/hpckit:2024.1.1-devel-ubuntu22.04` does not have this issue. It may be an issue with the public key for that particular build. Can you please take a look at it? That container is the base image of many of our software. 

Thank you very much!

**Comment by tingleby** [comment]
One of the reasons we released 2024.1.1 images is to fix this issue. Either, update to the latest, or you can refetch the latest gpu gpg key with 
`curl -fsSL https://repositories.intel.com/gpu/intel-graphics.key | gpg --dearmor | tee /usr/share/keyrings/intel-graphics-archive-keyring.gpg`

**Comment by jasonleekungfu** [comment]
Thank you very much! I will give it a try.

**Comment by jasonleekungfu** [comment]
I tried the newest version. I am compiling cp2k (or more specifically, ELPA). It automatically finds "mpiifort" as Fortran compiler, and complains "OpenMP unsupported". It did not happen yesterday when I was using 2024.1.0 image. Is this a known issue? I prefer not to hack their code if not necessary. Thank you!

**Comment by gorozco1** [comment]
@jasonleekungfu  if the issue with the repo fingerprint is gone can we close this and if you have issues compiling and having issues like you describe can you open another issue please, we try to keep things as atomic as possible.

**Comment by tingleby** [comment]
This issue should be resolved with the latest images, please let us know if you have any other questions.
