### ISSUE TITLE
Ubuntu 24.04 support

### ISSUE THREAD

**Issue by kwaa** [intel/oneapi-containers#73]
https://hub.docker.com/layers/library/ubuntu/24.04/images/sha256-3963c438d67a34318a3672faa6debd1dfff48e5d52de54305988b932c61514ca?context=explore

tags should be `2024.2.0-devel-ubuntu24.04` and `latest`.

**Comment by DatCaptainHorse** [comment]
For those that are as impatient as me, here's a quickly put together 24.04 version of basekit, tested that it can see my A770 
 which the official 22.04 image cannot.
https://github.com/users/DatCaptainHorse/packages/container/package/oneapi-basekit

Also here's the Dockerfile it was built with.
[Dockerfile.txt](https://github.com/user-attachments/files/16322285/Dockerfile.txt)

**Comment by mrcghil** [comment]
If you are looking for the 24.04 version of the HPCKIT, I got that running just by specifying that version in the FROM statement at the top. I have not run extensive tests with it though. Let me know if you want us to open a PR as there are no contribution guidelines here.

**Comment by tingleby** [comment]
With the 2025.0.0 release of the oneAPI toolkits, Ubuntu 24.04 is supported.
