### ISSUE TITLE
Add zlib

### ISSUE THREAD

**Issue by nathanweeks** [intel/oneapi-containers#8]
Could the zlib-devel (or at least zlib) package be installed in the intel/oneapi-hpckit:devel-centos8 image? It's not available in a path that can be readily linked to from C/C++, which presents difficulties when attempting to build software that links against it (`-lz`):
```
$ singularity pull docker://intel/oneapi-hpckit:devel-centos8
...
$ singularity exec --containall oneapi-hpckit_devel-centos8.sif find / -name libz.so 2>/dev/null
/opt/intel/oneapi/compiler/2021.1.1/linux/lib/oclfpga/host/linux64/lib/libz.so
/opt/intel/oneapi/intelpython/python3.7/envs/2021.1.1/lib/libz.so
/opt/intel/oneapi/intelpython/python3.7/lib/libz.so
/opt/intel/oneapi/intelpython/python3.7/pkgs/zlib-1.2.11.1-hb8a9d29_3/lib/libz.so
```

**Comment by gabrielbriones** [comment]
@nathanweeks libz.so is already included, so there is no need to install it from centos repository, it will be a better solution to just update the linker to look for libz.so in the correct path, this can be done with the env variable LD_LIBRARY_PATH

**Comment by nathanweeks** [comment]
@gabrielbriones Would the first one (/opt/intel/oneapi/compiler/2021.1.1/linux/lib/oclfpga/host/linux64/lib/libz.so
) be the best choice?

Since zlib is possibly the most widely-deployed software library (per https://sqlite.org/mostdeployed.html), and it seems a substantial amount of software that I attempt to compile (or dependencies) links against it, it would be convenient if adding an an`-lz` to the link options worked out of the box.

**Comment by gabrielbriones** [comment]
@nathanweeks This worked for me:

```
$ docker run --rm -ti intel/oneapi-hpckit:devel-ubuntu18.04
root@2997758c08e7:/# gcc zpipe.c -o zpipe -lz
zpipe.c:18:10: fatal error: zlib.h: No such file or directory
 #include "zlib.h"
          ^~~~~~~~
compilation terminated.
root@2997758c08e7:/# export C_INCLUDE_PATH=/opt/intel/oneapi/intelpython/python3.7/include
root@2997758c08e7:/# export LIBRARY_PATH=/opt/intel/oneapi/intelpython/python3.7/lib
root@2997758c08e7:/# gcc zpipe.c -o zpipe -lz
root@2997758c08e7:/# echo $?
0
```

**Comment by nathanweeks** [comment]
Thanks @gabrielbriones ! The `LIBRARY_PATH` environment variable looks like it would override a default value:
https://github.com/intel/oneapi-containers/blob/31963c34e66819ec80ef6db9ec0a9a43a4b681c4/images/docker/hpckit-devel-ubuntu18.04/Dockerfile#L60
It would be great if Intel perhaps updated the aforementioned LIBRARY_PATH environment variable to append /opt/intel/oneapi/intelpython/python3.7/lib (if that's "officially supported")

**Comment by gabrielbriones** [comment]
@nathanweeks I talked to the oneAPI dev team, and this zlib is not an intel-provided package, is just a dependency for a component build for oneAPI, that's the reason why is not included as part of the env variables. The quickest workaround would be to install the package yourself on the container, otherwise we would need to assess this issue to assign impact and business need prior to include zlib as part of oneAPI containers.

**Comment by nathanweeks** [comment]
@gabrielbriones Thanks for the explanation. Given the implicit goal and user expectation of better application performance when using oneAPI container images, perhaps [zlib-ng](https://github.com/zlib-ng/zlib-ng), which just hit its v2.0 stable release milestone, might be considered? Or maybe the suite of standard compression libraries (including zlib) accelerated by the [Intel Performance Primitives (IPP) Data Compression Domain](https://techdecoded.intel.io/resources/building-fast-data-compression-code-for-cloud-and-edge-applications/)?

In the meantime, I'll follow your advice and create a oneAPI-derived container image with zlib installed.
