### ISSUE TITLE
Reduce image size

### ISSUE THREAD

**Issue by pums974** [intel/oneapi-containers#9]
Hi, 

I would like to use the oneapi-hpckit container for my gitlab-ci pipeline but your image is too large (~23Go) for my registry.

Would it be possible to have a minimalist container with only the compiler (and the necessary libs) and not all the tools ?

Thanks

**Comment by gabrielbriones** [comment]
@pums974 This is something we have on track, you can expect this on a future release. On the meantime, as a workaround, you can use the Dockerfile as an example for building your own container.

**Comment by casperfrx** [comment]
Amazing, I had the same question.

It would be very helpful to me to know which packages are required for the compiler alone and for the python distribution. I  only want the compiler and the python distribution (with its optimized math packages) to be fair. Right now I just copied the Dockerfile but it is way too big. Could you tell me which packages I need for this smaller build?

Currently looks like this:

```
RUN true \
    && dnf install -y \
        dnf-plugins-core \
# Intel® oneAPI Common License
        intel-oneapi-common-licensing \
# Intel® oneAPI Common Environment Scripts
        intel-oneapi-common-vars \
# Intel® oneAPI Math Kernel Library
        intel-oneapi-mkl-devel \
# Intel® oneAPI DPC++/C++ Compiler
        intel-oneapi-compiler-dpcpp-cpp \ 
# Intel® Distribution for Python
        intel-oneapi-python \
# Intel® oneAPI Data Analytics Library Development Package
        intel-oneapi-dal-devel \ 
# Intel® Integrated Performance Primitives
        intel-oneapi-ipp-devel \ 
# Intel® Integrated Performance Primitives Cryptography
        intel-oneapi-ippcp-devel
```


Thanks in advance!

**Comment by bertwesarg** [comment]
its not only too large for the GitLab registry, it is also too large for the GitLab runners:

> write /opt/intel/oneapi/intelpython/python3.9/envs/2022.2.1/lib/libippiy8.so.10.5: no space left on device (manager.go:237:373s)

**Comment by pums974** [comment]
Have you made some progress on this ?

My current attempt to have a minimal docker container for gitlab-ci and my (fortran+mpi+python) project have the following (almost minimal) dependencies :
        intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic
        intel-oneapi-libdpstd-devel
        intel-oneapi-compiler-dpcpp-cpp
        intel-oneapi-compiler-fortran
        intel-oneapi-mpi-devel
        intel-oneapi-python
        
And this weight around 17 GB (and 15min just for building the image)

As a reference, my container for testing with GCC weight around 3Go.

**Comment by bertwesarg** [comment]
I'm still rebuilding my own container by modifying the Dockerfile. My current package list for 2024.0.1 is:

 - `intel-oneapi-common-vars`
 - `intel-oneapi-common-licensing`
 - `intel-oneapi-common-oneapi-vars`
 - `intel-oneapi-tlt`
 - `intel-basekit-getting-started-2024.0`
 - `intel-basekit-env-2024.0`
 - `intel-oneapi-dpcpp-ct`
 - `intel-oneapi-dev-utilities`
 - `intel-oneapi-libdpstd-devel-2022.3`
 - `intel-oneapi-diagnostics-utility`
 - `intel-opencl-icd`
 - `intel-level-zero-gpu`
 - `level-zero`
 - `level-zero-dev`
 - `intel-hpckit-getting-started-2024.0`
 - `intel-hpckit-env-2024.0`
 - `intel-oneapi-tlt`
 - `intel-oneapi-mpi-devel`
 - `intel-oneapi-compiler-dpcpp-cpp`
 - `intel-oneapi-compiler-fortran`

`docker image list` says it has a size 6.14 GB, DockerHub 1.91 GB.

`intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic` should be avoided starting with 2024.0.0, as it is not available anymore in this version, it basically means that you have two full compiler versions installed, the last 2023.x.y for the _classic_ and 2024.0.2 for the new compiler.

**Comment by tingleby** [comment]
With the release of 2025.0 oneAPI toolkits, we have introduced smaller toolkits/bundles.
For instance a C++ Essentials is a smaller version of the base toolkit that might be suitable.
`docker pull intel/cpp-essentials:latest`

Details can be seen on https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit.html 

Closing due to product change and age. If you have feedback or requests for other bundle, please let us know.

**Comment by bertwesarg** [comment]
This issue was specific to the `oneapi-hpckit` container, and their I don’ see any reduced/`essentials` images. Please reopen the issue. Thanks.
